module.exports = {
    JOB_TITLES: [
        { value: 'web-development', label: 'Web Development' },
        { value: 'software-engineer', label: 'Software Engineer' },
        { value: 'systems-engineer', label: 'Systems Engineer' },
        { value: 'software-developer', label: 'Software Developer' },
        { value: 'application-developer', label: 'Application Developer' },
        { value: 'mobile-development', label: 'Mobile Development' },
        { value: 'front-end-developement', label: 'Front-end Developement' },
        { value: 'back-end-developement', label: 'Back-end Developement' },
        { value: 'embedded-software-engineer', label: 'Embedded Software Engineer' },
        { value: 'dev-ops-engineer', label: 'DevOps Engineer' },
        { value: 'data-science', label: 'Data Science' },
        { value: 'application-development', label: 'Application Development' },
        { value: 'api-development', label: 'API Development' },
        { value: 'hobbyist', label: 'Hobbyist' },
    ],
    LANGUAGES_FRAMEWORKS: [
        { value: 'android', label: 'Android' },
        { value: 'angularjs', label: 'AngularJS' },
        { value: 'apache', label: 'Apache' },
        { value: 'appcelerator', label: 'aApcelerator' },
        { value: 'apple', label: 'Apple' },
        { value: 'babel', label: 'Babel' },
        { value: 'backbonejs', label: 'BackboneJS' },
        { value: 'c', label: 'C' },
        { value: 'cakephp', label: 'CakePHP' },
        { value: 'ceylon', label: 'Ceylon' },
        { value: 'codeigniter', label: 'Codeigniter' },
        { value: 'coffeescript', label: 'Coffeescript' },
        { value: 'couchdb', label: 'CouchDB' },
        { value: 'cplusplus', label: 'C++' },
        { value: 'csharp', label: 'C#' },
        { value: 'css3', label: 'CSS3' },
        { value: 'cucumber', label: 'Cucumber' },
        { value: 'd3js', label: 'D3js' },
        { value: 'django', label: 'django' },
        { value: 'docker', label: 'Docker' },
        { value: 'doctrine', label: 'Doctrine' },
        { value: 'drupal', label: 'Drupal' },
        { value: 'electron', label: 'Electron' },
        { value: 'elm', label: 'elm' },
        { value: 'ember', label: 'Ember' },
        { value: 'erlang', label: 'Erlang' },
        { value: 'express', label: 'Express' },
        { value: 'foundation', label: 'Foundation' },
        { value: 'gatling', label: 'Gatling' },
        { value: 'go', label: 'Go' },
        { value: 'gradle', label: 'Gradle' },
        { value: 'grunt', label: 'Grunt' },
        { value: 'gulp', label: 'Gulp' },
        { value: 'handlebars', label: 'Handlebars' },
        { value: 'html5', label: 'HTML5' },
        { value: 'ionic', label: 'Ionic' },
        { value: 'jasmine', label: 'Jasmine' },
        { value: 'java', label: 'Java' },
        { value: 'javascript', label: 'Javascript' },
        { value: 'jetbrains', label: 'Jetbrains' },
        { value: 'krakenjs', label: 'krakenjs' },
        { value: 'laravel', label: 'Laravel' },
        { value: 'less', label: 'LESS' },
        { value: 'linux', label: 'Linux' },
        { value: 'meteor', label: 'Meteor' },
        { value: 'mocha', label: 'Mocha' },
        { value: 'mongodb', label: 'MongoDB' },
        { value: 'mysql', label: 'Mysql' },
        { value: 'nginx', label: 'Nginx' },
        { value: 'nodejs', label: 'NodeJS' },
        { value: 'nodewebkit', label: 'Nodewebkit' },
        { value: 'php', label: 'PHP' },
        { value: 'postgresql', label: 'Postgresql' },
        { value: 'protractor', label: 'Protractor' },
        { value: 'pycharm', label: 'Pycharm' },
        { value: 'python', label: 'Python' },
        { value: 'rails', label: 'Rails' },
        { value: 'react', label: 'React' },
        { value: 'redhat', label: 'Redhat' },
        { value: 'redis', label: 'Redis' },
        { value: 'ruby', label: 'Ruby' },
        { value: 'rubymine', label: 'Rubymine' },
        { value: 'sass', label: 'SASS' },
        { value: 'sequelize', label: 'Sequelize' },
        { value: 'swift', label: 'Swift' },
        { value: 'symfony', label: 'Symfony' },
        { value: 'typescript', label: 'Typescript' },
        { value: 'vagrant', label: 'Vagrant' },
        { value: 'vuejs', label: 'VueJS' },
        { value: 'webpack', label: 'Webpack' },
        { value: 'yii', label: 'Yii' },
        { value: 'zend', label: 'Zend' },
    ],
};
